xmin: -100
ymin: -100
ymax: 100
xmax: 100
ogain: 3.0
minimumScore: 0
angularUpdate: 0.25
linearUpdate: 1.0
map_update_interval: 5.0
temporal_update: 5.0
odom_frame: odom
particles: 40
srr: 0.01
srt: 0.02
str: 0.01
stt: 0.02
delta: 0.05
maxUrange: 30
maxRange: 60
