## Local planner configuration
base_local_planner: base_local_planner/TrajectoryPlannerROS

local_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 2
    publish_frequency: 0.2
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.02
    transform_tolerance: 0.15
    track_unknown_space: true
    unknown_cost_value: 255

    plugins:
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

    footprint: [ [-0.2,-0.2], [0.2, -0.2], [0.2, 0.2], [-0.2,0.2] ]
    footprint_padding: 0.0

    obstacle_layer:
        enabled: true
        max_obstacle_height: 0.6  # assume something like an arm is mounted on top of the robot
        min_obstacle_height: 0.0
        obstacle_range: 30.0
        raytrace_range: 30.0
        observation_sources: base_scan
        base_scan:
            data_type: LaserScan
            sensor_frame: base_laser_link
            topic: /base_scan
            marking: true
            clearing: true
            max_obstacle_height: 0.6
            min_obstacle_height: 0.0
            expected_update_rate: 0.4

    inflation_layer:
          enabled:             true
          cost_scaling_factor: 7.5 # default value 10; for my work, I have been using values between 40-50
          inflation_radius:    0.3 # 0.35 works more or less fine; default value 0.55

    static_layer:
          enabled: true
          map_topic: /map
          subscribe_to_updates: true

controller_frequency: 20.0
recovery_behavior_enabled: true
clearing_rotation_allowed: false

recovery_behaviors: [{name: aggressive_clearance, type: clear_costmap_recovery/ClearCostmapRecovery}]
aggressive_clearance:
    reset_distance: 0.0

max_replanning_tries: 3
planner_patience: 5.0
planner_frequency: 0.2
controller_patience: 15.0

TrajectoryPlannerROS:
    max_vel_x: 0.85
    min_vel_x: 0.05 # set to negative with DWAPlannerROS to allow backward motion, doesn't work with TPR
#     NOTE: min_vel_x MUST be positive (cannot be zero) to work with TPR, can be negative with DWA
#     max_vel_y: 0.0 #P3AT is a differential drive robot
#     min_vel_y: 0.0 #P3AT is a differential drive robot
    max_vel_theta: 0.7
    min_vel_theta: -0.7
    acc_lim_theta: 2.5
    acc_lim_x: 1.5 # 0.50
    acc_lim_y: 1.5 # 0.50
    min_in_place_vel_theta: 0.4 # deprecated: min_in_place_rotational_vel
    escape_vel: -0.1
    escape_reset_dist: 0.15
    escape_reset_theta: 0.15

    holonomic_robot: false
    yaw_goal_tolerance: 0.2
    xy_goal_tolerance: 0.3 # 0.55
    latch_xy_goal_tolerance: false # default
    pdist_scale: 0.6 # 5.0
    gdist_scale: 0.8 # 0.8
    meter_scoring: true

    occdist_scale: 0.05 # obstacle avoidance, default 0.01
    oscillation_reset_dist: 0.25
    oscillation_reset_timeout: 10.0
    prune_plan: false

    sim_time: 1.5 # 1.8
    sim_granularity: 0.025
    vx_samples: 10
    vtheta_samples: 20

    dwa: true


## Global planner configuration
base_global_planner: global_replanner/GlobalReplanner

global_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 2
    publish_frequency: 0.1
    transform_tolerance: 0.25
    track_unknown_space: true
    unknown_cost_value: 255

    plugins:
        - {name: static_layer, type: "costmap_2d::StaticLayer"}
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

    footprint: [ [-0.2,-0.2], [0.2, -0.2], [0.2, 0.2], [-0.2,0.2] ]
    footprint_padding: 0.0

    obstacle_layer:
        enabled: true
        max_obstacle_height: 0.6  # assume something like an arm is mounted on top of the robot
        min_obstacle_height: 0.0
        obstacle_range: 30.0
        raytrace_range: 30.0
        observation_sources: base_scan
        base_scan:
            data_type: LaserScan
            sensor_frame: base_laser_link
            topic: /base_scan
            marking: true
            clearing: true
            max_obstacle_height: 0.6
            min_obstacle_height: 0.0
            expected_update_rate: 0.4

    inflation_layer:
          enabled:             true
          cost_scaling_factor: 7.5 # default value 10; for my work, I have been using values between 40-50
          inflation_radius:    2.25 # 0.35 works more or less fine; default value 0.55

    static_layer:
          enabled: true
          map_topic: /map
          subscribe_to_updates: true
 
GlobalReplanner:
    old_navfn_behavior: true
    allow_unknown: true
    track_unknown_space: true
    default_tolerance: 0.0

