global_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 2
    publish_frequency: 0.1
    static_map: true
    transform_tolerance: 0.25
    track_unknown_space: true
    unknown_cost_value: 255

    plugins:
        - {name: static_layer, type: "costmap_2d::StaticLayer"}
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

    footprint: [ [-0.2,-0.2], [0.2, -0.2], [0.2, 0.2], [-0.2,0.2] ]
    footprint_padding: 0.0

    obstacle_layer:
        enabled: true
        max_obstacle_height: 0.6  # assume something like an arm is mounted on top of the robot
        min_obstacle_height: 0.0
        obstacle_range: 30.0
        raytrace_range: 30.0
        observation_sources: base_scan
        base_scan: {data_type: LaserScan, sensor_frame: base_laser_link, topic: /base_scan, marking: true, clearing: true, max_obstacle_height: 0.6, min_obstacle_height: 0.0, expected_update_rate: 0.4}

    inflation_layer:
          enabled:             true
          cost_scaling_factor: 7.5 # default value 10; for my work, I have been using values between 40-50
          inflation_radius:    2.25 # 0.35 works more or less fine; default value 0.55

    static_layer:
          enabled: true
          map_topic: /map
          subscribe_to_updates: true
 
GlobalReplanner:
    old_navfn_behavior: true
    allow_unknown: true
    track_unknown_space: true
#    use_dijkstra: false
#    use_quadratic: true
#    use_grid_path: true
    default_tolerance: 0.0

